import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Button from "@/components/button";
import {DropdownMenu} from "@/components/dropdown";
import AlertDialogDemo from "@/components/alert";

const inter = Inter({ subsets: ['latin'] })

export default function Components() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Button>
                    I am a button
                </Button>
                <DropdownMenu/>
                <AlertDialogDemo/>
            </main>
        </>
    )
}
